<a href="https://colab.research.google.com/github/hmyrcmn/bitirme/blob/main/ModelDecrib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers torch

import json
from transformers import BertTokenizer, BertModel
import torch

# JSON dosyasını oku
json_data = """
{
    "name": "Mehmet Aydın",
    "industry": "Manufacturing, Automotive, Robotics",
    "competence": [
        "Product Development",
        "Supply Chain Management",
        "Quality Control",
        "Operations Optimization"
    ],
    "focus": [
        "Robotics",
        "Automotive"
    ]
}
"""

# JSON verisini Python sözlüğüne dönüştür
data = json.loads(json_data)

# BERT tokenizer ve modelini yükle
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Her bir anahtarı ve değeri tokenleştir ve sayısal temsilleri al
for key, value in data.items():
    # Metni tokenleştir
    tokens = tokenizer(value, return_tensors='pt', padding=True, truncation=True)

    # Tokenleri modele giriş yap
    outputs = model(**tokens)

    # İlk gizli katmanın (embeddings) çıktılarını al
    embeddings = outputs.last_hidden_state

    # İlk tokenün sayısal temsilini yazdır
    print(f"Anahtar: {key}")
    print("Tokenler:")
    print(tokens)
    print("Sayısal Temsil:")
    print(embeddings[0])
    print("\n")


  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Anahtar: name
Tokenler:
{'input_ids': tensor([[  101,  2033, 14227,  3388,  1037, 25688, 11722,  2078,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}
Sayısal Temsil:
tensor([[-0.3733,  0.6114, -0.2928,  ..., -0.2387,  0.4976, -0.1394],
        [ 0.2043, -0.5555, -1.4085,  ..., -0.5304,  0.3348,  0.3770],
        [ 0.5222,  0.1803, -0.9473,  ..., -0.9417, -0.0476, -0.8228],
        ...,
        [ 0.3169, -0.2497, -0.7269,  ..., -1.3072,  0.0249, -0.4597],
        [ 0.4086, -0.0642, -1.0634,  ..., -0.7716, -0.2047,  0.1960],
        [ 0.6366,  0.0127, -0.3634,  ...,  0.2735, -0.6065, -0.4111]],
       grad_fn=<SelectBackward0>)


Anahtar: industry
Tokenler:
{'input_ids': tensor([[  101,  5814,  1010, 12945,  1010, 21331,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
Sayısal Temsil:
tensor([[ 0.1081, -0.0452, -0.2784,  ..., -0.3611,  0.3584,  0.382

In [2]:
import torch
from transformers import BertTokenizer, BertModel

# BERT modeli ve tokenizer'ını yükle
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# İki örnek JSON veri
cv_json = {
    "name": "Selma Yılmaz",
    "industry": "Fashion, Retail, E-commerce",
    "competence": [
        "Brand Management",
        "Market Research",
        "E-commerce Strategy",
        "Visual Merchandising"
    ],
    "focus": [
        "Fashion",
        "E-commerce"
    ]
}

startup_json = {
    "title": "Poland",
    "business_name": "PlayerGo",
    "category": "Poland",
    "based_in": "Krakow",
    "tags": "games, hardware, controllers, gaming, videogames",
    "founded": "2010"
}

# Her iki JSON verisi için işlemleri gerçekleştir
for data_name, data in [("CV", cv_json), ("Startup", startup_json)]:
    print(f"{data_name} JSON Verisi:")
    print(data)
    print("\n")

    # Her bir anahtar ve değer için işlem yap
    for key, value in data.items():
        print(f"Anahtar: {key}")
        print(f"Metin: {value}")

        # Metni tokenleştir
        tokens = tokenizer(value, return_tensors='pt', padding=True, truncation=True)
        print("Tokenler:")
        print(tokens)

        # Tokenlerin sayısal temsilini al
        with torch.no_grad():
            outputs = model(**tokens)
            last_hidden_state = outputs.last_hidden_state.mean(dim=1)
        print("Sayısal Temsil:")
        print(last_hidden_state)
        print("\n")

    print("---------------------------------------------------\n")


CV JSON Verisi:
{'name': 'Selma Yılmaz', 'industry': 'Fashion, Retail, E-commerce', 'competence': ['Brand Management', 'Market Research', 'E-commerce Strategy', 'Visual Merchandising'], 'focus': ['Fashion', 'E-commerce']}


Anahtar: name
Metin: Selma Yılmaz
Tokenler:
{'input_ids': tensor([[  101, 28112,  1061, 11722, 19145,  2480,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
Sayısal Temsil:
tensor([[ 1.2750e-01, -1.0676e-01, -3.2623e-01,  1.9940e-02,  1.5194e-01,
         -1.6852e-01,  4.6832e-01,  3.6464e-01, -2.6994e-01, -2.0681e-01,
          6.5793e-01, -6.6634e-01, -4.1170e-01,  3.5100e-01, -5.9999e-01,
          1.1901e-01, -8.3988e-02,  2.7653e-01, -5.9289e-01,  9.4421e-01,
          1.5200e-01, -1.6028e-01,  8.3626e-02,  1.3727e-01, -2.6980e-01,
          3.5192e-01, -3.4703e-01,  3.5000e-01,  1.4705e-01,  5.3352e-01,
         -7.1254e-01, -3.6752e-01, -1.9997e-01, -3.4997e-01, -4.9152e-02,
         -1.0231e-01,